name: Workflow name
run-name: Workflow name run name
on: push
jobs:
  firstJob:
    name: "first job"
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "hello world!"
