name: Tests
run-name: Tests run
on: workflow_dispatch
jobs:
  firstJob:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-docker-action@v5
      - uses: actions/checkout@v6
      - name: Docker build
        run: docker build cypress:pipeline .
      - name: Docker run
        run: docker run cypress:pipeline
