name: Tests
run-name: Tests run
on: workflow_dispatch
jobs:
  firstJob:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Npm install
        run: npm install
      - name: run tests
        run: npm run cy:run
